
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeff
 */
public class agendarCita extends javax.swing.JFrame {

    private static Connection con;
    private static final String url = "jdbc:mysql://localhost:3306/ProyectoMigracion";
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";

    String fechaCompleta;

    public void conector() {
        // Reseteamos a null la conexion a la bd
        con = null;
        try {
            Class.forName(driver);
            // Nos conectamos a la bd
            con = (Connection) DriverManager.getConnection(url, user, pass);
            // Si la conexion fue exitosa mostramos un mensaje de conexion exitosa
            if (con != null) {
                //JOptionPane.showMessageDialog(null, "Conexion Exitosa");
            }
        } // Si la conexion NO fue exitosa mostramos un mensaje de error
        catch (ClassNotFoundException | SQLException e) {
            //JOptionPane.showMessageDialog(null, "Conexion Fallida");
        }
    }

    public void limpiar() {
        //txtPais.setText("");
        txtDepartamento.setText("");
        txtMunicipio.setText("");
        cbxCentro.setSelectedIndex(0);
        cbxDia.setSelectedIndex(0);
        cbxMes.setSelectedIndex(0);
        cbxAño.setSelectedIndex(0);
        cbxHorario.setSelectedIndex(0);
    }

    public agendarCita() {
        initComponents();
        jlbDia.setVisible(false);
        jlbMes.setVisible(false);
        jlbAño.setVisible(false);
        jlbHorario.setVisible(false);
        
        Inf_Personal ventana = new Inf_Personal();
        txtDepartamento.setText(ventana.gDep);
        txtMunicipio.setText(ventana.gMun);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxCentro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        cbxMes = new javax.swing.JComboBox<>();
        cbxAño = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxHorario = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        jlbDia = new javax.swing.JLabel();
        jlbMes = new javax.swing.JLabel();
        jlbAño = new javax.swing.JLabel();
        jlbHorario = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pais: *");

        txtPais.setEditable(false);
        txtPais.setText("Guatemala");

        jLabel2.setText("Departamento: *");

        jLabel3.setText("Municipio: *");

        jLabel4.setText("Centro: *");

        cbxCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "PASAPORTES CENTRAL" }));

        jLabel5.setText("Fecha:");

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbxAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "2021", "2022", "2023", "2024", "2025" }));

        jLabel6.setText("Día *");

        jLabel7.setText("Mes *");

        jLabel8.setText("Año *");

        jLabel9.setText("Horario: *");

        cbxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "8 am", "9 am", "10 am", "11 am", "12 am", "1 pm", "2 pm", "3 pm", "4 pm" }));

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jlbDia.setText(".");

        jlbMes.setText(".");

        jlbAño.setText(".");

        jlbHorario.setText(".");

        txtMunicipio.setEditable(false);

        txtDepartamento.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbAño)
                                    .addComponent(jlbHorario)
                                    .addComponent(jlbMes)
                                    .addComponent(jlbDia)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtPais)
                            .addComponent(cbxCentro, 0, 165, Short.MAX_VALUE)
                            .addComponent(txtDepartamento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel7)))
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addComponent(jlbDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbAño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbHorario)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        try {
            String nuevaFecha, anioBD, mesBD, diaBD, horarioBD;
            String anioBD2, mesBD2, diaBD2, horarioBD2;
            String anioBD3, mesBD3, diaBD3, horarioBD3;
            String conDepartamento, conMunicipio, conCentro, conDia, conMes;
            String conAnio, conHorario;

            Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ProyectoMigracion", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into agendar values(?,?,?,?,?,?,?)");

            Connection cn2 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ProyectoMigracion", "root", "");
            PreparedStatement pst2 = cn2.prepareStatement("select * from agendar where pais_agendar = ?");

            Connection cn3 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/ProyectoMigracion", "root", "");
            PreparedStatement pst3 = cn3.prepareStatement("select * from agendar where horario = ?");

            //Buscar si se repite
            pst2.setString(1, txtPais.getText().trim());
            pst3.setString(1, cbxHorario.getSelectedItem().toString());

            ResultSet rs = pst2.executeQuery();
            ResultSet rs2 = pst3.executeQuery();

            if (rs.next() && rs2.next()) {
                nuevaFecha = rs.getString("fecha");
                anioBD = nuevaFecha.split("-")[0];
                mesBD = nuevaFecha.split("-")[1];
                diaBD = nuevaFecha.split("-")[2];

                jlbDia.setText(diaBD);
                jlbMes.setText(mesBD);
                jlbAño.setText(anioBD);

                horarioBD = rs2.getString("horario");
                jlbHorario.setText(horarioBD);
            }

            //Capturo los valores para luego compararlos
            anioBD2 = cbxAño.getSelectedItem().toString();
            mesBD2 = cbxMes.getSelectedItem().toString();
            diaBD2 = cbxDia.getSelectedItem().toString();
            horarioBD2 = cbxHorario.getSelectedItem().toString();

            //Capturo en variables los datos de la Base de datos
            anioBD3 = jlbAño.getText();
            mesBD3 = jlbMes.getText();
            diaBD3 = jlbDia.getText();
            horarioBD3 = jlbHorario.getText();

            //Capturo los valores para luego validar que no esten vacios
            conDepartamento = txtDepartamento.getText();
            conMunicipio = txtMunicipio.getText();
            conCentro = cbxCentro.getSelectedItem().toString();
            conDia = cbxDia.getSelectedItem().toString();
            conMes = cbxMes.getSelectedItem().toString();;
            conAnio = cbxAño.getSelectedItem().toString();
            conHorario = cbxHorario.getSelectedItem().toString();

            if (conDepartamento != "Selecciona" && conMunicipio.length() != 0
                    && conCentro != "Selecciona" && conDia != "Selecciona"
                    && conMes != "Selecciona" && conAnio != "Selecciona"
                    && conHorario != "Selecciona") {
                if (anioBD2.equals(anioBD3) && mesBD2.equals(mesBD3)
                        && diaBD2.equals(diaBD3) && horarioBD2.equals(horarioBD3)) {
                    JOptionPane.showMessageDialog(null, "Lo sentimos, el horario o dia que has elegido no se encuentra disponible");
                } else {
                    pst.setString(1, "0");
                    pst.setString(2, txtPais.getText().trim());
                    pst.setString(3, txtDepartamento.getText().trim());
                    pst.setString(4, txtMunicipio.getText().trim());
                    pst.setString(5, cbxCentro.getSelectedItem().toString());
                    fechaCompleta = cbxAño.getSelectedItem().toString() + "-"
                            + cbxMes.getSelectedItem().toString() + "-"
                            + cbxDia.getSelectedItem().toString();
                    pst.setString(6, fechaCompleta);
                    pst.setString(7, cbxHorario.getSelectedItem().toString());
                    pst.executeUpdate();
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Su cita a sido agendada.");
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Todos los campos tienen que estar llenos.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agendarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cbxAño;
    private javax.swing.JComboBox<String> cbxCentro;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxHorario;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlbAño;
    private javax.swing.JLabel jlbDia;
    private javax.swing.JLabel jlbHorario;
    private javax.swing.JLabel jlbMes;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
