
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static java.time.Clock.system;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author leone
 */
public class Inf_Personal extends javax.swing.JFrame {

    /**
     * Creates new form Inf_Personal
     */
    public Inf_Personal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public static String gCorreo = "";
    public static String gPais = "";
    public static String gDep = "";
    public static String gMun = "";
    public static String gDir = "";
    public static String gCel = "";
    public static String gAlt = "";
    public static String gOjos = "";
    public static String gTez = "";
    public static String gOcupa = "";
    public static String gnombrec = "";
    public static String gnacionalidad = "";
    public static String gEstadoCiil = "";
    public static String gsexo = "";
    public static String gfechaDnacimiento = "";
    public static String gdpi = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomDepartamento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nomPais = new javax.swing.JTextField();
        nomMunicipio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomDireccion = new javax.swing.JTextField();
        numCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nomCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nomConfirmacionCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numAltura = new javax.swing.JTextField();
        nomTez = new javax.swing.JTextField();
        nomOjos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nomOcupacion = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        noIdentificacion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nomTramite = new javax.swing.JComboBox<>();
        nomPasaporte = new javax.swing.JComboBox<>();
        nomCaso = new javax.swing.JComboBox<>();
        aceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        NombreC = new javax.swing.JLabel();
        FechaDnacimiento = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JLabel();
        EstadoCiil = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("INFORMACIÓN PERSONAL");

        jLabel2.setText("País: *");

        jLabel3.setText("Departamento Residencia: *");

        nomDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Alta Verapaz", "Baja Verapaz", "Chimaltenago", "Chiquimula", "Guatemala", "El Progreso", "Escuintla", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Petén", "Quetzaltenango", "Quiché", "Retalhuleu", "Sacatepequez", "San Marcos", "Santa Rosa", "Sololá", "Suchitepequez", "Totonicapán", "Zacapa" }));

        jLabel4.setText("Municipio Residencia: *");

        nomPais.setText("Guatemala");
        nomPais.setEnabled(false);

        jLabel5.setText("Dirección Residencial: *");

        jLabel6.setText("Celular: *");

        jLabel7.setText("Telefono:");

        jLabel8.setText("Correo Electronico: *");

        jLabel9.setText("Confirme Correo Electronico: *");

        jLabel10.setText("Altura: *");

        jLabel11.setText("Tez: *");

        jLabel12.setText("Ojos: *");

        numAltura.setText("Altura en cm.");

        jLabel13.setText("Ocupación: *");

        nomOcupacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Administración de Empresas e Ingeniería Comercial", "Marketing y Mercadotecnia", "Contabilidad y Auditoría", "Industrial", "Informática y Sistemas", "Recursos Humanos y Relación Industrial", "Mecánica y Metalúrgica", "Finanzas", "Química", "Psicología", "Otros" }));

        jLabel14.setText("No. De Identificación: *");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("* CAMPOS OBLIGATORIOS");

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel16.setText("INFORMACIÓN DE SOLICITUD DE PASAPORTE:");

        jLabel17.setText("Tipo de Tramite:");

        jLabel18.setText("Tipo de Pasaporte:");

        jLabel19.setText("Tipo de Caso:");

        nomTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Pasaporte por primera vez para persona adulta.", "Renovación de pasaporte para persona adulta.", "Pasaporte por primera vez para menor de edad", "Renovación de pasaporte para menor de edad", "Reposición de pasaporte por robo, extravío o mutilación", "Pasaporte de emergencia" }));

        nomPasaporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Ordinario", "Temporal", "Diplomatico", "Oficial" }));

        nomCaso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Menor de edad", "Extranjero residente de Guatemala", " " }));
        nomCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomCasoActionPerformed(evt);
            }
        });

        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreC)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(nomPais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(41, 41, 41)
                                                        .addComponent(jLabel3))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(40, 40, 40)
                                                        .addComponent(nomDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jLabel5)
                                            .addComponent(nomDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(numAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(30, 30, 30))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(95, 95, 95)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nomTez, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(99, 99, 99)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(nomCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(nomMunicipio)
                                            .addComponent(numCelular)
                                            .addComponent(nomConfirmacionCorreo)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nomOjos)))
                                    .addComponent(numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nomOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(noIdentificacion))))
                                .addComponent(nomPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(343, 343, 343)
                                    .addComponent(nomCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nomTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(EstadoCiil)
                                        .addGap(33, 33, 33)
                                        .addComponent(sexo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FechaDnacimiento))
                                    .addComponent(jLabel15))
                                .addContainerGap(37, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nacionalidad)
                                .addGap(66, 66, 66))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomConfirmacionCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomTez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomOjos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(sexo))
                        .addGap(18, 18, 18)
                        .addComponent(nomTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(nomPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NombreC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(EstadoCiil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nacionalidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FechaDnacimiento)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
int paso1=0;
        String mmDepartamento = "", mmOcupacion = "";
        mmDepartamento = nomDepartamento.getSelectedItem().toString();
        mmOcupacion = nomOcupacion.getSelectedItem().toString();
        gCorreo = nomCorreo.getText();
        gPais = nomPais.getText();
        gDep = mmDepartamento;
        gMun = nomMunicipio.getText();
        gDir = nomDireccion.getText();
        gCel = numCelular.getText();
        gAlt = numAltura.getText();
        gOjos = nomOjos.getText();
        gTez = nomTez.getText();
        gOcupa = mmOcupacion;
        String nDepartamento = "", nOcupacion = "";
        String tTramite = "", tPasaporte = "", tCaso = "";
        tTramite = nomTramite.getSelectedItem().toString();
        tPasaporte = nomPasaporte.getSelectedItem().toString();
        tCaso = nomCaso.getSelectedItem().toString();
        nDepartamento = nomDepartamento.getSelectedItem().toString();
        nOcupacion = nomOcupacion.getSelectedItem().toString();

        if (nomMunicipio.getText().length() != 0 && nomDireccion.getText().length() != 0 && numCelular.getText().length() != 0 && numTelefono.getText().length() != 0 // cuenta los caractares de cada campo si es diferente de 0 lo deja pasar
                && nomCorreo.getText().length() != 0 && nomConfirmacionCorreo.getText().length() != 0 && numAltura.getText().length() != 0 && nomTez.getText().length() != 0
                && nomOjos.getText().length() != 0 && nDepartamento != "Seleccionar..." && nOcupacion != "Seleccionar..." && tTramite != "Seleccionar..."
                && tPasaporte != "Seleccionar..." && tCaso != "Seleccionar...") {
            if (nomCorreo.getText().equals(nomConfirmacionCorreo.getText())) //para que el correo sea igual    
            {
                try {
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proyectomigracion", "root", "");//Conecta con la base de datos nomina
                    PreparedStatement pst = cn.prepareStatement("select * from Renap where DPI = ?");//Busca la variable noBoleta en la tabla de la base de datos
                    pst.setString(1, noIdentificacion.getText().trim());
                    ResultSet rs = pst.executeQuery();

                    if (rs.next()) {//Captura las variables string y las convertimos a labels
                        NombreC.setText(rs.getString("NombreC"));
                        FechaDnacimiento.setText(rs.getString("FechaDnacimiento"));
                        nacionalidad.setText(rs.getString("nacionalidad"));
                        EstadoCiil.setText(rs.getString("EstadoCiil"));
                        sexo.setText(rs.getString("sexo"));
                        gnombrec = NombreC.getText();
                        gfechaDnacimiento = FechaDnacimiento.getText();
                        gEstadoCiil = EstadoCiil.getText();
                        gnacionalidad = nacionalidad.getText();
                        gdpi = noIdentificacion.getText();
                        gsexo = sexo.getText();
                        paso1=1;
                        NombreC.setText("");
                        FechaDnacimiento.setText("");
                        nacionalidad.setText("");
                        EstadoCiil.setText("");
                        sexo.setText("");

                    } else {
                        JOptionPane.showMessageDialog(null, "DPI no encontrado.");//Si no lo encuentra envia un mensaje de error
                        noIdentificacion.setText("");
                    }
                } catch (Exception e) {
                    System.out.print(e.getMessage());
                }
                if (paso1==1) {
                try {
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proyectomigracion", "root", "");
                    PreparedStatement pst = cn.prepareStatement("insert into datospersonales values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    pst.setString(1, "0");
                    pst.setString(2, noIdentificacion.getText().trim());
                    pst.setString(3, nomCorreo.getText().trim());
                    pst.setString(4, numTelefono.getText().trim());
                    pst.setString(5, numCelular.getText().trim());
                    pst.setString(6, nOcupacion.trim());
                    pst.setString(7, nomPais.getText().trim());
                    pst.setString(8, nDepartamento.trim());
                    pst.setString(9, nomMunicipio.getText().trim());
                    pst.setString(10, nomDireccion.getText().trim());
                    pst.setString(11, numAltura.getText().trim());
                    pst.setString(12, nomTez.getText().trim());
                    pst.setString(13, nomOjos.getText().trim());
                    pst.executeUpdate();
                } catch (Exception e) {
                    System.out.print(e.getMessage());
                }
                try {
                    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/proyectomigracion", "root", "");
                    PreparedStatement pst = cn.prepareStatement("insert into datospasaporte values(?,?,?,?,?)");
                    pst.setString(1, "0");
                    pst.setString(2, noIdentificacion.getText().trim());
                    pst.setString(3, tTramite.trim());
                    pst.setString(4, tPasaporte.trim());
                    pst.setString(5, tCaso.trim());
                    pst.executeUpdate();
                    Verificacion_Inf_Personal ventana = new Verificacion_Inf_Personal();
                    ventana.setVisible(true);
                    this.setVisible(false);
                } catch (Exception e) {
                    System.out.print(e.getMessage());
                }    
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Correos no coinciden");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void nomCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomCasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomCasoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // creador Gerson para cerrar el programa
       confirmarsalida();
    }//GEN-LAST:event_btncancelarActionPerformed
public void confirmarsalida(){
    int valor=JOptionPane.showConfirmDialog(this,"Estas seguro de cerrar el programa?","Advertencia",JOptionPane.YES_NO_OPTION);
    if (valor==JOptionPane.YES_OPTION){
    System.exit(0);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inf_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inf_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inf_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inf_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inf_Personal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EstadoCiil;
    private javax.swing.JLabel FechaDnacimiento;
    private javax.swing.JLabel NombreC;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nacionalidad;
    private javax.swing.JTextField noIdentificacion;
    private javax.swing.JComboBox<String> nomCaso;
    private javax.swing.JTextField nomConfirmacionCorreo;
    private javax.swing.JTextField nomCorreo;
    private javax.swing.JComboBox<String> nomDepartamento;
    private javax.swing.JTextField nomDireccion;
    private javax.swing.JTextField nomMunicipio;
    private javax.swing.JComboBox<String> nomOcupacion;
    private javax.swing.JTextField nomOjos;
    private javax.swing.JTextField nomPais;
    private javax.swing.JComboBox<String> nomPasaporte;
    private javax.swing.JTextField nomTez;
    private javax.swing.JComboBox<String> nomTramite;
    private javax.swing.JTextField numAltura;
    private javax.swing.JTextField numCelular;
    private javax.swing.JTextField numTelefono;
    private javax.swing.JLabel sexo;
    // End of variables declaration//GEN-END:variables
}
